services:
  sonar:
    image: sonarqube:10.4-community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - 9000:9000
    networks:
      - sonar
  
  ngrok:
    profiles:
      - public
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - http
      - http://sonar:9000
      - --domain
      - ${NGROK_DOMAIN}
    ports:
      - 4040:4040
    networks:
      - sonar
      
networks:
  sonar:
    name: sonar

volumes:
  sonarqube_data:
    external: false
  sonarqube_logs:
    external: false
  sonarqube_extensions:
    external: false